version: '3'
services:
  authservice:
    container_name: authservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: ${UID}
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: khoadev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth-db
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
  pgadmin:


